### ISSUE TITLE
"Filter with the same name already exists! Aborting"

### ISSUE THREAD

**Issue by clemense** [JenniferBuehler/gazebo-pkgs#17]
Hi,
The plugin doesn't work in my case as expected (objects are not attached). During loading I get the following output:
```
Loading grasp-fix plugin
GazeboGraspFix: Using disable_collisions_on_attach 0
GazeboGraspFix: Using update rate 4
GazeboGraspFix: Using max_grip_count 100
GazeboGraspFix: Using grip_count_threshold 4
GazeboGraspFix: Using release_tolerance 0.1005
GazeboGraspFix: Adding collision scoped name yumi::gripper_r_finger_l::gripper_r_finger_l_collision
GazeboGraspFix: Adding collision scoped name yumi::gripper_r_finger_r::gripper_r_finger_r_collision
[Err] [ContactManager.cc:282] Filter with the same name already exists! Aborting
Subscribing contact manager to topic 
```

1) Is it crucial to avoid the error that comes from the contact manager to make the plugin work?
2) If yes, have you experienced this before / do you know a fix?  (Googling the error lead me to this: https://bitbucket.org/osrf/gazebo/issues/960/allow-multiple-contactsensor-per-collision   which should be solved in the Gazebo version I'm using [7.0.0])

Thanks!

**Comment by clemense** [comment]
Ok, I found the problem. I accidentally added the plug-in to both grippers.
But even with one, it doesn't have any effect. Apart from the initial output during loading:
```
Loading grasp-fix plugin
GazeboGraspFix: Using disable_collisions_on_attach 0
GazeboGraspFix: Using update rate 4
GazeboGraspFix: Using max_grip_count 8
GazeboGraspFix: Using grip_count_threshold 4
GazeboGraspFix: Using release_tolerance 0.005
GazeboGraspFix: Adding collision scoped name yumi::gripper_r_finger_l::gripper_r_finger_l_collision
GazeboGraspFix: Adding collision scoped name yumi::gripper_r_finger_r::gripper_r_finger_r_collision
Subscribing contact manager to topic ~/yumi/contacts
```
there is nothing.
How can I debug this?

**Comment by JenniferBuehler** [comment]
Can you post the output when the robot grips the object? A prerequisite for grasping it is that there are contacts with the grippers, so either  ``yumi::gripper_r_finger_l::gripper_r_finger_l_collision`` or ``yumi::gripper_r_finger_l::gripper_r_finger_l_collision`` and the object. Also note that collision is required with the collision shape of the robot, not the visual (you can display collision shapes in gazebo under the "View" menu).

For debugging, I'd suggest printf debugging starting in function [OnUpdate()](https://github.com/JenniferBuehler/gazebo-pkgs/blob/f4700ea772e4757ed6a0ebffb50a288dd131dcf4/gazebo_grasp_plugin/src/GazeboGraspFix.cpp#L358). I can help if you send me your output.

**Comment by clemense** [comment]
I played around with the parameters and got it somehow to work.

**Comment by FrankLin9981** [comment]
> I played around with the parameters and got it somehow to work.

Excuse me! Could I ask you how you got it work.
