### ISSUE TITLE
Project 'gazebo_world_plugin_loader' specifies

### ISSUE THREAD

**Issue by DylanLN** [JenniferBuehler/gazebo-pkgs#40]
Hello, I want to ask if the plugin now supports ros-melodic + gazebo9

**Comment by JenniferBuehler** [comment]
Sorry for the late reply!
It should be supported, but I haven't tried in in a while and I can't remember if I did that already on Melodic. I'm happy to do updates though, if required.
Can you follow the tutorials and report whether you have any issues?

**Comment by JenniferBuehler** [comment]
I'll be working on melodic support throghout the week. Meantime, I had forgotten that there is the branch `melodic-support` but it needs some updates.
Since there has been no more discussion in this thread for a while, I consider this closed. Please re-open if required.
