### ISSUE TITLE
Ground Collision

### ISSUE THREAD

**Issue by Kaushik093** [JenniferBuehler/gazebo-pkgs#55]
My robotic arm is colliding with the ground when traversing from one point to another. Is there any way to disable collisions with the ground?

**Comment by JenniferBuehler** [comment]
You could try [collision bitmask](https://classic.gazebosim.org/tutorials?tut=collide_bitmask&cat=physics).

However I'd rather try to improve the robot control so that it does not touch the ground plane. When you program a real robot that's what you'd like to achieve as well...
