### ISSUE TITLE
the object does not get between the grippers.

### ISSUE THREAD

**Issue by mco528** [JenniferBuehler/gazebo-pkgs#59]
Hi, Jennifer. I'm trying to get a 3 DOF voice-controlled robot to do the pick and place operation. The grippers can't fully grasp and lift the object. When I give the command to lift the arm, the arm lifts up, but the object does not rise. What can I do to get the body up along with the arm ?

**Comment by JenniferBuehler** [comment]
Hi. I'm sorry for the late response. I didn't see this before now. I recommend you look at the wiki, the grasp plugin has to be set up for the robot.
