### ISSUE TITLE
Unable to pick object properly by open manipulator arm in gazebo ROS2

### ISSUE THREAD

**Issue by mayank0621** [JenniferBuehler/gazebo-pkgs#60]
Hi @JenniferBuehler hope you are doing well, I'm using ROS2 humble and trying to use your plugin for my manipulator to grasp an object. But it's not working, In your humble branch of GitHub I have seen the CMakeLists.txt is for ROS1. So could you please check once.
     Thanks in advance!!!

**Comment by JenniferBuehler** [comment]
Hi,
The humble branch is actually still the master state. I recently created it for a PR that was meant to be coming, see #57. You can try the code in https://github.com/kongoncharuk/gazebo-pkgs/tree/humble

**Comment by mayank0621** [comment]
Thanks @JenniferBuehler for your reply.
     I've tried above plugin in ROS2 humble but its not working for me. I'm attaching some screenshot. Any help would be great for me. 

Here I have added plugin
![e7155e31-cad8-4194-94f8-fb3823469c15](https://github.com/JenniferBuehler/gazebo-pkgs/assets/98181895/d7d02d0c-3cdb-4aa9-b220-1d16cf2024f8)

This the path of "libgazebo_grasp_fix.so" file 
![fe26928c-174a-478e-8012-a948cced1f21](https://github.com/JenniferBuehler/gazebo-pkgs/assets/98181895/e36bfe95-dbd9-4c1f-a8ba-96b606fc7dc1)

Logs of terminal when I'm executing launch file
![image](https://github.com/JenniferBuehler/gazebo-pkgs/assets/98181895/80e3797e-6741-4311-8b95-63e944b486a2)


Gazebo contact topic:
![7e898777-2a52-422e-9a0e-eccbbddcab1d](https://github.com/JenniferBuehler/gazebo-pkgs/assets/98181895/a1202ae0-33e6-416f-9f63-1c1cfa082216)

This is the behavior  of my arm

![image](https://github.com/JenniferBuehler/gazebo-pkgs/assets/98181895/eb5733db-b620-4463-8b46-7dca4061b542)

**Comment by Aki1608** [comment]
> Hi, The humble branch is actually still the master state. I recently created it for a PR that was meant to be coming, see #57. You can try the code in https://github.com/kongoncharuk/gazebo-pkgs/tree/humble

Hi @JenniferBuehler, I tried using that humble branch but at the time of build, I am getting the following error:

```
CMake Error at /home/aki/ws_moveit2/install/gazebo_grasp_plugin/share/gazebo_grasp_plugin/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
  Package 'gazebo_grasp_plugin' exports the library 'gazebo_grasp_fix' which
  couldn't be found
Call Stack (most recent call first):
  /home/aki/ws_moveit2/install/gazebo_grasp_plugin/share/gazebo_grasp_plugin/cmake/gazebo_grasp_pluginConfig.cmake:41 (include)
  CMakeLists.txt:15 (find_package)
```
I assume that without this package, this plugin will not work, right?

Do you have any idea what can be the error here?

**Comment by JenniferBuehler** [comment]
Hi ,
The plugin is Ros independent (just gazebo), for ros2 only the makefiles changed.
The output you sent are not from the plugin. Maybe it's not loaded. Do you see any `GazeboGraspFix` output?
Please also refer to the troubleshooting page on the wiki.
I'm not sure when I'll have time to test, but I'll try

**Comment by JenniferBuehler** [comment]
Did you set the GAZEBO_PLUGIN_PATH?

**Comment by Aki1608** [comment]
> CMake Error at /home/aki/ws_moveit2/install/gazebo_grasp_plugin/share/gazebo_grasp_plugin/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
>   Package 'gazebo_grasp_plugin' exports the library 'gazebo_grasp_fix' which
>   couldn't be found
> Call Stack (most recent call first):
>   /home/aki/ws_moveit2/install/gazebo_grasp_plugin/share/gazebo_grasp_plugin/cmake/gazebo_grasp_pluginConfig.cmake:41 (include)
>   CMakeLists.txt:15 (find_package)

Hi @JenniferBuehler, changing some file directory solved the issue. But it looks like the plugin is not being loaded. I dont see any logs of this plugin.

**Comment by Aki1608** [comment]
Also, There are only three packages in humble branch which are converted to ros2. Do I need all the packages for the desired behavior? Or only "gazebo_grasp_plugin" and "gazebo_grasp_plugin_ros" packages which are converted into the ROS2 humble format? 

What I want to say is that I am not building other packages, namely, "gazebo_state_plugins", "gazebo_world_plugin_loader", "gazebo_test_tools". So I am hist removing from the directory while building the package. Will that work or these three packages are also important to have to load the plugin?

**Comment by Aki1608** [comment]
HI @JenniferBuehler, I was able to load the plugin but when I am trying to move the object after grasping, the arm starts shaking and then it deforms. 

I also get this error:

```
TF_NAN_INPUT: Ignoring transform for child_frame_id "gripper_link" from authority "Authority undetectable" because of a nan value in the transform (-nan -nan -nan) (0.000000 0.000000 0.000000 1.000000)
[move_group-7]          at line 235 in ./src/buffer_core.cpp
[move_group-7] Error:   TF_NAN_INPUT: Ignoring transform for child_frame_id "gripper_link_sub" from authority "Authority undetectable" because of a nan value in the transform (-nan -nan -nan) (0.000000 0.000000 0.000000 1.000000)

```
What can be the error here? I tried playing with some parameters of the plugin as well.

**Comment by Aki1608** [comment]
Hi @JenniferBuehler, I was able to solve all errors. Thank you so much for your help. It is working properly in ROS2 humble.

**Comment by mayank0621** [comment]
Hi @JenniferBuehler I have solved all issues. Error was in the gazebo world file. Also I have to change path of libgazebo_grasp_fix.so file so that it can be detected.
  Thanks a lot for your support!!!!!

**Comment by JenniferBuehler** [comment]
Ah, just as I get around to check the messages, you already solved it. Great, well done :)

**Comment by beta1scat** [comment]
> Hi @JenniferBuehler, I was able to solve all errors. Thank you so much for your help. It is working properly in ROS2 humble.

Hi [Aki1608](https://github.com/Aki1608), I am encountering a similar issue with ROS2 Humble. Would you kindly provide me with further details on how to resolve this matter? Your assistance is greatly appreciated.
I also only build three packages:
```
colcon build --packages-select gazebo_grasp_plugin gazebo_grasp_plugin_ros gazebo_version_helpers
```
Before build I also modified the `gazebo_grasp_plugin`:
```
<!-- <buildtool_depend>catkin</buildtool_depend> -->
  <buildtool_depend>ament_cmake</buildtool_depend>
```
`gazebo_grasp_plugin_ros` doesn't build successful and get errors:
```
CMake Error at /root/ws_host/install/gazebo_grasp_plugin/share/gazebo_grasp_plugin/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
  Package 'gazebo_grasp_plugin' exports the library 'gazebo_grasp_fix' which
  couldn't be found
Call Stack (most recent call first):
  /root/ws_host/install/gazebo_grasp_plugin/share/gazebo_grasp_plugin/cmake/gazebo_grasp_pluginConfig.cmake:41 (include)
  CMakeLists.txt:15 (find_package)
```

**Comment by beta1scat** [comment]
> > Hi @JenniferBuehler, I was able to solve all errors. Thank you so much for your help. It is working properly in ROS2 humble.
> 
> Hi [Aki1608](https://github.com/Aki1608), I am encountering a similar issue with ROS2 Humble. Would you kindly provide me with further details on how to resolve this matter? Your assistance is greatly appreciated. I also only build three packages:
> 
> ```
> colcon build --packages-select gazebo_grasp_plugin gazebo_grasp_plugin_ros gazebo_version_helpers
> ```
> 
> Before build I also modified the `gazebo_grasp_plugin`:
> 
> ```
> 
>   <buildtool_depend>ament_cmake</buildtool_depend>
> ```
> 
> `gazebo_grasp_plugin_ros` doesn't build successful and get errors:
> 
> ```
> CMake Error at /root/ws_host/install/gazebo_grasp_plugin/share/gazebo_grasp_plugin/cmake/ament_cmake_export_libraries-extras.cmake:48 (message):
>   Package 'gazebo_grasp_plugin' exports the library 'gazebo_grasp_fix' which
>   couldn't be found
> Call Stack (most recent call first):
>   /root/ws_host/install/gazebo_grasp_plugin/share/gazebo_grasp_plugin/cmake/gazebo_grasp_pluginConfig.cmake:41 (include)
>   CMakeLists.txt:15 (find_package)
> ```

I've successfully resolved the issue by removing the `\${PROJECT_NAME}` reference from the `gazbo_grasp_plugin` `CMakeLists.txt` file. If you're using ROS2 Humble, feel free to give this a try. If it proves helpful, I would greatly appreciate your feedback.
