### ISSUE TITLE
Grasp Plugin for ROS2

### ISSUE THREAD

**Issue by saianurag234** [JenniferBuehler/gazebo-pkgs#61]
How to make this package supports ROS2

**Comment by JenniferBuehler** [comment]
There is a branch called "humble" which you can try

**Comment by saianurag234** [comment]
Can you provide the installation instructions

**Comment by architjain19** [comment]
The humble branch doesn't contains any ros2 content. The packages are still related to ros1 (their CMakeLists.txt, pckage.xml and other files are in ros1 format). I guess they have just duplicated the branch and renamed to humble

**Comment by JenniferBuehler** [comment]
Hi, sorry I remembered this wrong. Someone made the adaptation for humble but never sent the PR which I created the branch for. See #57 . You can find the code there.
