### ISSUE TITLE
The problem of objects penetrating each other after the gripper clamps the object

### ISSUE THREAD

**Issue by Liyiyang66** [JenniferBuehler/gazebo-pkgs#62]
Hello, I want to collect the torque information generated by the collision at the joint, but after the gripper clamps the object, the object will pass through other objects. What should I do?
![image](https://github.com/JenniferBuehler/gazebo-pkgs/assets/112848342/af92aaae-cca7-4837-926e-f3dc0e235fe8)
![image](https://github.com/JenniferBuehler/gazebo-pkgs/assets/112848342/2599c569-1cff-4850-91f5-f83d12f1a5cb)

This is information about the object：
![image](https://github.com/JenniferBuehler/gazebo-pkgs/assets/112848342/7411005f-c43b-4bd8-8310-c4be8254b1d1)
![image](https://github.com/JenniferBuehler/gazebo-pkgs/assets/112848342/06f2ec65-4de4-4620-a16a-9d464b1ad46d)

**Comment by JenniferBuehler** [comment]
Hi, did you try to add `<self_collide>1</self_collide>` to the link of the object?

**Comment by Liyiyang66** [comment]
oh，thanks for your advice, the problem has been solved.

**Comment by JenniferBuehler** [comment]
Great, that's good to hear! May I asked what resolved it?

**Comment by Liyiyang66** [comment]
I used gazebo to re-export the more detailed parameter configuration， and set the <self_collide>1</self_collide>, then the object will colide the table, the force and torque change as well.

**Comment by JenniferBuehler** [comment]
Thanks for the info :)
