### ISSUE TITLE
Gripper penetrates object in Gazebo，why？

### ISSUE THREAD

**Issue by liujun0808** [JenniferBuehler/gazebo-pkgs#64]
When the clamping jaw is closed, the terminal prompts that the object has been grasped, but the clamping jaw remains closed until it penetrates the object. Why is this?
![{2RX1E}QO(J$NEA9OI~NPNE](https://github.com/JenniferBuehler/gazebo-pkgs/assets/148852180/efcba23f-eee3-4da4-9713-4379ae8165a6)
Has anyone encountered this situation? Looking forward to your reply, thank you!

**Comment by liujun0808** [comment]
The object is defined by myself, the following is its description.
![V~S{XPQ082IL)PSJRDR_Y(6](https://github.com/JenniferBuehler/gazebo-pkgs/assets/148852180/2774382c-e023-4dd1-afd7-b6081bd7b1a7)
![image](https://github.com/JenniferBuehler/gazebo-pkgs/assets/148852180/42861f06-6c30-4892-9c35-6b28087ff46e)

**Comment by JenniferBuehler** [comment]
The object will be attached to the robot but if your control is still closing the gripper, it will keep moving. Though there won't be collisions causing the object and robot to fly off into space ;) the grasp plugin does not handle your grippe control, only the attachment. You should close your gripper only as much as you know is necessary to cause a collision with the object. If it goes a bit beyond, that doesn't matter. The object will still be released once you open the gripper again.

**Comment by JenniferBuehler** [comment]
If you need a notification on when attachment happens, so you can stop the movement: an event message is published. See [this example](https://github.com/JenniferBuehler/gazebo-pkgs/blob/master/gazebo_grasp_plugin_ros/src/grasp_event_republisher.cpp) which is subscribing to it (if you are using ROS, you can also use the ROS message which is published by this code in the link)

**Comment by liujun0808** [comment]
> If you need a notification on when attachment happens, so you can stop the movement: an event message is published. See [this example](https://github.com/JenniferBuehler/gazebo-pkgs/blob/master/gazebo_grasp_plugin_ros/src/grasp_event_republisher.cpp) which is subscribing to it (if you are using ROS, you can also use the ROS message which is published by this code in the link)

Thank you!!!!!Your answer gave me new ideas. I will try it and report back to you if I get good results.

**Comment by JenniferBuehler** [comment]
Glad I could help :)
I'll close this now, please reopen if there are more comments.
